name: ntwaza
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # Navigation & State Management
  go_router: ^14.6.2
  provider: ^6.1.2

  # Realtime
  socket_io_client: ^2.0.3+1
  
  # Networking
  http: ^1.2.0
  
  # Storage
  shared_preferences: ^2.3.3
  
  # Location & Maps
  geolocator: ^13.0.2
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  location: ^5.0.0
  flutter_polyline_points: ^2.0.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  
  # Media
  image_picker: ^1.0.4
  
  # Utilities
  timeago: ^3.6.1
  logger: ^2.0.0
  url_launcher: ^6.2.1
  intl: ^0.19.0
  timezone: ^0.9.2

# Force compatible web implementations
dependency_overrides:
  geolocator_web: 4.1.1
  firebase_messaging_web: 3.8.6
  web: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ntwaza_splash.png
